"""Transition table for the production-scoped shadow bundle ladder."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

TransitionKind = Literal["plan", "proof", "request", "grant", "run", "review"]


@dataclass(frozen=True)
class ShadowTransition:
    revision: int
    name: str
    kind: TransitionKind
    from_revision: int
    from_next_stage_constant: str | None
    to_revision: int
    to_next_stage_constant: str
    plan_mode: str
    expect_flag_name: str | None
    bundle_revision_constant: str
    payload_verifier_name: str | None
    strip_fn_name: str | None = None
    apply_fn_name: str | None = None
    section_verifier_name: str | None = None
    prior_chain_verifier_name: str | None = None
    filed_marker_path: str | None = None
    introduced_blocker: str | None = None
    cleared_blocker: str | None = None
    scope_constant: str | None = None


TRANSITIONS: tuple[ShadowTransition, ...] = (
    ShadowTransition(
        revision=1,
        name="production scoped shadow plan",
        kind="plan",
        from_revision=0,
        from_next_stage_constant=None,
        to_revision=1,
        to_next_stage_constant="POST_PLAN_NEXT_STAGE",
        plan_mode="post_plan",
        expect_flag_name="expect_plan_filed",
        bundle_revision_constant="POST_PLAN_BUNDLE_REVISION",
        payload_verifier_name=None,
        apply_fn_name="apply_production_scoped_shadow_plan",
        filed_marker_path="plan.prod_scoped_shadow_plan_defined",
    ),
    ShadowTransition(
        revision=2,
        name="production scoped shadow proof",
        kind="proof",
        from_revision=1,
        from_next_stage_constant="POST_PLAN_NEXT_STAGE",
        to_revision=2,
        to_next_stage_constant="POST_PROOF_NEXT_STAGE",
        plan_mode="post_proof",
        expect_flag_name="expect_proof_filed",
        bundle_revision_constant="POST_PROOF_BUNDLE_REVISION",
        payload_verifier_name=None,
        apply_fn_name="apply_production_scoped_shadow_proof",
        section_verifier_name="_verify_proof_section",
        filed_marker_path="posture.prod_scoped_shadow_proof_passed",
    ),
    ShadowTransition(
        revision=3,
        name="pilot authorization request",
        kind="request",
        from_revision=2,
        from_next_stage_constant="POST_PROOF_NEXT_STAGE",
        to_revision=3,
        to_next_stage_constant="POST_PILOT_REQUEST_NEXT_STAGE",
        plan_mode="post_pilot_request",
        expect_flag_name="expect_pilot_request_filed",
        bundle_revision_constant="POST_PILOT_REQUEST_BUNDLE_REVISION",
        payload_verifier_name=None,
        apply_fn_name="apply_production_scoped_shadow_pilot_authorization_request",
        filed_marker_path="authorization.prod_scoped_shadow_pilot_authorization_requested",
        scope_constant="PILOT_REQUEST_SCOPE",
    ),
    ShadowTransition(
        revision=4,
        name="pilot authorization grant",
        kind="grant",
        from_revision=3,
        from_next_stage_constant="POST_PILOT_REQUEST_NEXT_STAGE",
        to_revision=4,
        to_next_stage_constant="POST_PILOT_GRANT_NEXT_STAGE",
        plan_mode="post_pilot_grant",
        expect_flag_name="expect_pilot_grant_filed",
        bundle_revision_constant="POST_PILOT_GRANT_BUNDLE_REVISION",
        payload_verifier_name=None,
        apply_fn_name="apply_production_scoped_shadow_pilot_authorization_grant",
        filed_marker_path="authorization.prod_scoped_shadow_pilot_authorized",
        scope_constant="PILOT_GRANT_SCOPE",
    ),
    ShadowTransition(
        revision=5,
        name="pilot harness run",
        kind="run",
        from_revision=4,
        from_next_stage_constant="POST_PILOT_GRANT_NEXT_STAGE",
        to_revision=5,
        to_next_stage_constant="POST_PILOT_HARNESS_NEXT_STAGE",
        plan_mode="post_pilot_harness",
        expect_flag_name="expect_pilot_harness_filed",
        bundle_revision_constant="POST_PILOT_HARNESS_BUNDLE_REVISION",
        payload_verifier_name=None,
        apply_fn_name="apply_production_scoped_shadow_pilot_harness",
        section_verifier_name="_verify_pilot_harness_section",
        filed_marker_path="execution.prod_scoped_shadow_pilot_harness_executed",
    ),
    ShadowTransition(
        revision=6,
        name="pilot harness review",
        kind="review",
        from_revision=5,
        from_next_stage_constant="POST_PILOT_HARNESS_NEXT_STAGE",
        to_revision=6,
        to_next_stage_constant="POST_PILOT_HARNESS_REVIEW_ACCEPTED_NEXT_STAGE",
        plan_mode="post_pilot_harness_review",
        expect_flag_name="expect_pilot_harness_review_filed",
        bundle_revision_constant="POST_PILOT_HARNESS_REVIEW_BUNDLE_REVISION",
        payload_verifier_name=None,
        apply_fn_name="apply_production_scoped_shadow_pilot_harness_review",
        section_verifier_name="_verify_pilot_harness_review_section",
        filed_marker_path="review.prod_scoped_shadow_pilot_harness_reviewed",
    ),
    ShadowTransition(
        revision=7,
        name="pilot run",
        kind="run",
        from_revision=6,
        from_next_stage_constant="POST_PILOT_HARNESS_REVIEW_ACCEPTED_NEXT_STAGE",
        to_revision=7,
        to_next_stage_constant="POST_PILOT_RUN_NEXT_STAGE",
        plan_mode="post_pilot_run",
        expect_flag_name="expect_pilot_run_filed",
        bundle_revision_constant="POST_PILOT_RUN_BUNDLE_REVISION",
        payload_verifier_name=None,
        apply_fn_name="apply_production_scoped_shadow_pilot_run",
        section_verifier_name="_verify_pilot_run_section",
        filed_marker_path="execution.prod_scoped_shadow_pilot_executed",
    ),
    ShadowTransition(
        revision=8,
        name="pilot review",
        kind="review",
        from_revision=7,
        from_next_stage_constant="POST_PILOT_RUN_NEXT_STAGE",
        to_revision=8,
        to_next_stage_constant="POST_PILOT_REVIEW_ACCEPTED_NEXT_STAGE",
        plan_mode="post_pilot_review",
        expect_flag_name="expect_pilot_review_filed",
        bundle_revision_constant="POST_PILOT_REVIEW_BUNDLE_REVISION",
        payload_verifier_name=None,
        apply_fn_name="apply_production_scoped_shadow_pilot_review",
        section_verifier_name="_verify_pilot_review_section",
        filed_marker_path="review.prod_scoped_shadow_pilot_reviewed",
    ),
    ShadowTransition(
        revision=9,
        name="live read-only authorization request",
        kind="request",
        from_revision=8,
        from_next_stage_constant="POST_PILOT_REVIEW_ACCEPTED_NEXT_STAGE",
        to_revision=9,
        to_next_stage_constant="POST_LIVE_READ_ONLY_REQUEST_NEXT_STAGE",
        plan_mode="post_live_read_only_request",
        expect_flag_name="expect_live_read_only_request_filed",
        bundle_revision_constant="POST_LIVE_READ_ONLY_REQUEST_BUNDLE_REVISION",
        payload_verifier_name=None,
        apply_fn_name="apply_production_scoped_shadow_live_read_only_authorization_request",
        section_verifier_name="_verify_live_read_only_request_section",
        filed_marker_path="authorization.prod_scoped_shadow_live_read_only_authorization_requested",
        scope_constant="LIVE_READ_ONLY_REQUEST_SCOPE",
    ),
    ShadowTransition(
        revision=10,
        name="live read-only authorization grant",
        kind="grant",
        from_revision=9,
        from_next_stage_constant="POST_LIVE_READ_ONLY_REQUEST_NEXT_STAGE",
        to_revision=10,
        to_next_stage_constant="POST_LIVE_READ_ONLY_GRANT_NEXT_STAGE",
        plan_mode="post_live_read_only_grant",
        expect_flag_name="expect_live_read_only_grant_filed",
        bundle_revision_constant="POST_LIVE_READ_ONLY_GRANT_BUNDLE_REVISION",
        payload_verifier_name=None,
        apply_fn_name="apply_production_scoped_shadow_live_read_only_authorization_grant",
        section_verifier_name="_verify_live_read_only_grant_section",
        filed_marker_path="authorization.prod_scoped_shadow_live_read_only_authorization_granted",
        scope_constant="LIVE_READ_ONLY_GRANT_SCOPE",
    ),
    ShadowTransition(
        revision=11,
        name="live read-only pilot run",
        kind="run",
        from_revision=10,
        from_next_stage_constant="POST_LIVE_READ_ONLY_GRANT_NEXT_STAGE",
        to_revision=11,
        to_next_stage_constant="POST_LIVE_READ_ONLY_PILOT_RUN_NEXT_STAGE",
        plan_mode="post_live_read_only_pilot_run",
        expect_flag_name="expect_live_read_only_pilot_run_filed",
        bundle_revision_constant="POST_LIVE_READ_ONLY_PILOT_RUN_BUNDLE_REVISION",
        payload_verifier_name=None,
        apply_fn_name="apply_production_scoped_shadow_live_read_only_pilot_run",
        section_verifier_name="_verify_live_read_only_pilot_run_section",
        filed_marker_path="execution.prod_scoped_shadow_live_read_only_pilot_executed",
    ),
    ShadowTransition(
        revision=12,
        name="live read-only pilot review",
        kind="review",
        from_revision=11,
        from_next_stage_constant="POST_LIVE_READ_ONLY_PILOT_RUN_NEXT_STAGE",
        to_revision=12,
        to_next_stage_constant="POST_LIVE_READ_ONLY_PILOT_REVIEW_ACCEPTED_NEXT_STAGE",
        plan_mode="post_live_read_only_pilot_review",
        expect_flag_name="expect_live_read_only_pilot_review_filed",
        bundle_revision_constant="POST_LIVE_READ_ONLY_PILOT_REVIEW_BUNDLE_REVISION",
        payload_verifier_name="_verify_live_read_only_pilot_review_payload",
        strip_fn_name="_without_live_read_only_pilot_review_payload",
        apply_fn_name="apply_production_scoped_shadow_live_read_only_pilot_review",
        section_verifier_name="_verify_live_read_only_pilot_review_section",
        filed_marker_path="review.prod_scoped_shadow_live_read_only_pilot_reviewed",
    ),
    ShadowTransition(
        revision=13,
        name="live execution authorization request",
        kind="request",
        from_revision=12,
        from_next_stage_constant="POST_LIVE_READ_ONLY_PILOT_REVIEW_ACCEPTED_NEXT_STAGE",
        to_revision=13,
        to_next_stage_constant="POST_LIVE_EXECUTION_REQUEST_NEXT_STAGE",
        plan_mode="post_live_execution_request",
        expect_flag_name="expect_live_execution_request_filed",
        bundle_revision_constant="POST_LIVE_EXECUTION_REQUEST_BUNDLE_REVISION",
        payload_verifier_name="_verify_live_execution_request_payload",
        strip_fn_name="_without_live_execution_request_payload",
        apply_fn_name="apply_production_scoped_shadow_live_execution_authorization_request",
        section_verifier_name="_verify_live_execution_request_section",
        filed_marker_path="authorization.prod_scoped_shadow_live_execution_authorization_requested",
        scope_constant="LIVE_EXECUTION_REQUEST_SCOPE",
    ),
    ShadowTransition(
        revision=14,
        name="live execution authorization grant",
        kind="grant",
        from_revision=13,
        from_next_stage_constant="POST_LIVE_EXECUTION_REQUEST_NEXT_STAGE",
        to_revision=14,
        to_next_stage_constant="POST_LIVE_EXECUTION_GRANT_NEXT_STAGE",
        plan_mode="post_live_execution_grant",
        expect_flag_name="expect_live_execution_grant_filed",
        bundle_revision_constant="POST_LIVE_EXECUTION_GRANT_BUNDLE_REVISION",
        payload_verifier_name="_verify_live_execution_grant_payload",
        strip_fn_name="_without_live_execution_grant_payload",
        apply_fn_name="apply_production_scoped_shadow_live_execution_authorization_grant",
        section_verifier_name="_verify_live_execution_grant_section",
        filed_marker_path="authorization.prod_scoped_shadow_live_execution_authorization_granted",
        scope_constant="LIVE_EXECUTION_GRANT_SCOPE",
    ),
    ShadowTransition(
        revision=15,
        name="live execution pilot run",
        kind="run",
        from_revision=14,
        from_next_stage_constant="POST_LIVE_EXECUTION_GRANT_NEXT_STAGE",
        to_revision=15,
        to_next_stage_constant="POST_LIVE_EXECUTION_PILOT_RUN_NEXT_STAGE",
        plan_mode="post_live_execution_pilot_run",
        expect_flag_name="expect_live_execution_pilot_run_filed",
        bundle_revision_constant="POST_LIVE_EXECUTION_PILOT_RUN_BUNDLE_REVISION",
        payload_verifier_name="_verify_live_execution_pilot_run_payload",
        strip_fn_name="_without_live_execution_pilot_run_payload",
        apply_fn_name="apply_production_scoped_shadow_live_execution_pilot_run",
        section_verifier_name="_verify_live_execution_pilot_run_section",
        filed_marker_path="execution.prod_scoped_shadow_live_execution_pilot_executed",
    ),
    ShadowTransition(
        revision=16,
        name="live execution pilot review",
        kind="review",
        from_revision=15,
        from_next_stage_constant="POST_LIVE_EXECUTION_PILOT_RUN_NEXT_STAGE",
        to_revision=16,
        to_next_stage_constant="POST_LIVE_EXECUTION_PILOT_REVIEW_ACCEPTED_NEXT_STAGE",
        plan_mode="post_live_execution_pilot_review",
        expect_flag_name="expect_live_execution_pilot_review_filed",
        bundle_revision_constant="POST_LIVE_EXECUTION_PILOT_REVIEW_BUNDLE_REVISION",
        payload_verifier_name="_verify_live_execution_pilot_review_payload",
        strip_fn_name="_without_live_execution_pilot_review_payload",
        apply_fn_name="apply_production_scoped_shadow_live_execution_pilot_review",
        section_verifier_name="_verify_live_execution_pilot_review_section",
        filed_marker_path="review.prod_scoped_shadow_live_execution_pilot_reviewed",
    ),
    ShadowTransition(
        revision=17,
        name="flag enablement authorization request",
        kind="request",
        from_revision=16,
        from_next_stage_constant="POST_LIVE_EXECUTION_PILOT_REVIEW_ACCEPTED_NEXT_STAGE",
        to_revision=17,
        to_next_stage_constant="POST_FLAG_ENABLEMENT_REQUEST_NEXT_STAGE",
        plan_mode="post_flag_enablement_request",
        expect_flag_name="expect_flag_enablement_request_filed",
        bundle_revision_constant="POST_FLAG_ENABLEMENT_REQUEST_BUNDLE_REVISION",
        payload_verifier_name="_verify_flag_enablement_request_payload",
        strip_fn_name="_without_flag_enablement_request_payload",
        apply_fn_name="apply_production_scoped_shadow_flag_enablement_authorization_request",
        section_verifier_name="_verify_flag_enablement_request_section",
        filed_marker_path="authorization.prod_scoped_shadow_flag_enablement_authorization_requested",
        scope_constant="FLAG_ENABLEMENT_REQUEST_SCOPE",
    ),
    ShadowTransition(
        revision=18,
        name="flag enablement authorization grant",
        kind="grant",
        from_revision=17,
        from_next_stage_constant="POST_FLAG_ENABLEMENT_REQUEST_NEXT_STAGE",
        to_revision=18,
        to_next_stage_constant="POST_FLAG_ENABLEMENT_GRANT_NEXT_STAGE",
        plan_mode="post_flag_enablement_grant",
        expect_flag_name="expect_flag_enablement_grant_filed",
        bundle_revision_constant="POST_FLAG_ENABLEMENT_GRANT_BUNDLE_REVISION",
        payload_verifier_name="_verify_flag_enablement_grant_payload",
        strip_fn_name="_without_flag_enablement_grant_payload",
        apply_fn_name="apply_production_scoped_shadow_flag_enablement_authorization_grant",
        section_verifier_name="_verify_flag_enablement_grant_section",
        filed_marker_path="authorization.prod_scoped_shadow_flag_enablement_authorization_granted",
        scope_constant="FLAG_ENABLEMENT_GRANT_SCOPE",
    ),
    ShadowTransition(
        revision=19,
        name="flag enablement pilot run",
        kind="run",
        from_revision=18,
        from_next_stage_constant="POST_FLAG_ENABLEMENT_GRANT_NEXT_STAGE",
        to_revision=19,
        to_next_stage_constant="POST_FLAG_ENABLEMENT_PILOT_RUN_NEXT_STAGE",
        plan_mode="post_flag_enablement_pilot_run",
        expect_flag_name="expect_flag_enablement_pilot_run_filed",
        bundle_revision_constant="POST_FLAG_ENABLEMENT_PILOT_RUN_BUNDLE_REVISION",
        payload_verifier_name="_verify_flag_enablement_pilot_run_payload",
        strip_fn_name="_without_flag_enablement_pilot_run_payload",
        apply_fn_name="apply_production_scoped_shadow_flag_enablement_pilot_run",
        section_verifier_name="_verify_flag_enablement_pilot_run_section",
        filed_marker_path="execution.prod_scoped_shadow_flag_enablement_pilot_executed",
    ),
    ShadowTransition(
        revision=20,
        name="flag enablement pilot review",
        kind="review",
        from_revision=19,
        from_next_stage_constant="POST_FLAG_ENABLEMENT_PILOT_RUN_NEXT_STAGE",
        to_revision=20,
        to_next_stage_constant="POST_FLAG_ENABLEMENT_PILOT_REVIEW_ACCEPTED_NEXT_STAGE",
        plan_mode="post_flag_enablement_pilot_review",
        expect_flag_name="expect_flag_enablement_pilot_review_filed",
        bundle_revision_constant="POST_FLAG_ENABLEMENT_PILOT_REVIEW_BUNDLE_REVISION",
        payload_verifier_name="_verify_flag_enablement_pilot_review_payload",
        strip_fn_name="_without_flag_enablement_pilot_review_payload",
        apply_fn_name="apply_production_scoped_shadow_flag_enablement_pilot_review",
        section_verifier_name="_verify_flag_enablement_pilot_review_section",
        filed_marker_path="review.prod_scoped_shadow_flag_enablement_pilot_reviewed",
    ),
    ShadowTransition(
        revision=21,
        name="production default API user-visible authorization request",
        kind="request",
        from_revision=20,
        from_next_stage_constant="POST_FLAG_ENABLEMENT_PILOT_REVIEW_ACCEPTED_NEXT_STAGE",
        to_revision=21,
        to_next_stage_constant="POST_PRODUCTION_DEFAULT_API_USER_VISIBLE_REQUEST_NEXT_STAGE",
        plan_mode="post_production_default_api_user_visible_request",
        expect_flag_name="expect_production_default_api_user_visible_request_filed",
        bundle_revision_constant="POST_PRODUCTION_DEFAULT_API_USER_VISIBLE_REQUEST_BUNDLE_REVISION",
        payload_verifier_name="_verify_production_default_api_user_visible_request_payload",
        strip_fn_name="_without_production_default_api_user_visible_request_payload",
        apply_fn_name="apply_production_scoped_shadow_production_default_api_user_visible_authorization_request",
        section_verifier_name="_verify_production_default_api_user_visible_request_section",
        filed_marker_path=(
            "authorization.prod_scoped_shadow_production_default_api_user_visible_authorization_requested"
        ),
        scope_constant="PRODUCTION_DEFAULT_API_USER_VISIBLE_REQUEST_SCOPE",
    ),
    ShadowTransition(
        revision=22,
        name="production default API user-visible authorization grant",
        kind="grant",
        from_revision=21,
        from_next_stage_constant="POST_PRODUCTION_DEFAULT_API_USER_VISIBLE_REQUEST_NEXT_STAGE",
        to_revision=22,
        to_next_stage_constant="POST_PRODUCTION_DEFAULT_API_USER_VISIBLE_GRANT_NEXT_STAGE",
        plan_mode="post_production_default_api_user_visible_grant",
        expect_flag_name="expect_production_default_api_user_visible_grant_filed",
        bundle_revision_constant="POST_PRODUCTION_DEFAULT_API_USER_VISIBLE_GRANT_BUNDLE_REVISION",
        payload_verifier_name="_verify_production_default_api_user_visible_grant_payload",
        strip_fn_name="_without_production_default_api_user_visible_grant_payload",
        apply_fn_name="apply_production_scoped_shadow_production_default_api_user_visible_authorization_grant",
        section_verifier_name="_verify_production_default_api_user_visible_grant_section",
        filed_marker_path=(
            "authorization.prod_scoped_shadow_production_default_api_user_visible_authorization_granted"
        ),
        scope_constant="PRODUCTION_DEFAULT_API_USER_VISIBLE_GRANT_SCOPE",
    ),
    ShadowTransition(
        revision=23,
        name="production default API user-visible pilot run",
        kind="run",
        from_revision=22,
        from_next_stage_constant="POST_PRODUCTION_DEFAULT_API_USER_VISIBLE_GRANT_NEXT_STAGE",
        to_revision=23,
        to_next_stage_constant="POST_PRODUCTION_DEFAULT_API_USER_VISIBLE_PILOT_RUN_NEXT_STAGE",
        plan_mode="post_production_default_api_user_visible_pilot_run",
        expect_flag_name="expect_production_default_api_user_visible_pilot_run_filed",
        bundle_revision_constant="POST_PRODUCTION_DEFAULT_API_USER_VISIBLE_PILOT_RUN_BUNDLE_REVISION",
        payload_verifier_name="_verify_production_default_api_user_visible_pilot_run_payload",
        strip_fn_name="_without_production_default_api_user_visible_pilot_run_payload",
        apply_fn_name="apply_production_scoped_shadow_production_default_api_user_visible_pilot_run",
        section_verifier_name="_verify_production_default_api_user_visible_pilot_run_section",
        filed_marker_path=(
            "execution.prod_scoped_shadow_production_default_api_user_visible_pilot_executed"
        ),
    ),
    ShadowTransition(
        revision=24,
        name="production default API user-visible pilot review",
        kind="review",
        from_revision=23,
        from_next_stage_constant="POST_PRODUCTION_DEFAULT_API_USER_VISIBLE_PILOT_RUN_NEXT_STAGE",
        to_revision=24,
        to_next_stage_constant="POST_PRODUCTION_DEFAULT_API_USER_VISIBLE_PILOT_REVIEW_ACCEPTED_NEXT_STAGE",
        plan_mode="post_production_default_api_user_visible_pilot_review",
        expect_flag_name="expect_production_default_api_user_visible_pilot_review_filed",
        bundle_revision_constant="POST_PRODUCTION_DEFAULT_API_USER_VISIBLE_PILOT_REVIEW_BUNDLE_REVISION",
        payload_verifier_name="_verify_production_default_api_user_visible_pilot_review_payload",
        strip_fn_name="_without_production_default_api_user_visible_pilot_review_payload",
        apply_fn_name="apply_production_scoped_shadow_production_default_api_user_visible_pilot_review",
        section_verifier_name="_verify_production_default_api_user_visible_pilot_review_section",
        filed_marker_path=(
            "review.prod_scoped_shadow_production_default_api_user_visible_pilot_reviewed"
        ),
    ),
    ShadowTransition(
        revision=25,
        name="controlled production recommendation authorization request",
        kind="request",
        from_revision=24,
        from_next_stage_constant="POST_PRODUCTION_DEFAULT_API_USER_VISIBLE_PILOT_REVIEW_ACCEPTED_NEXT_STAGE",
        to_revision=25,
        to_next_stage_constant="POST_CONTROLLED_PRODUCTION_RECOMMENDATION_REQUEST_NEXT_STAGE",
        plan_mode="post_controlled_production_recommendation_request",
        expect_flag_name="expect_controlled_production_recommendation_request_filed",
        bundle_revision_constant="POST_CONTROLLED_PRODUCTION_RECOMMENDATION_REQUEST_BUNDLE_REVISION",
        payload_verifier_name="_verify_controlled_production_recommendation_request_payload",
        strip_fn_name="_without_controlled_production_recommendation_request_payload",
        apply_fn_name="apply_production_scoped_shadow_controlled_production_recommendation_authorization_request",
        section_verifier_name="_verify_controlled_production_recommendation_request_section",
        filed_marker_path=(
            "authorization.prod_scoped_shadow_controlled_production_recommendation_authorization_requested"
        ),
        scope_constant="CONTROLLED_PRODUCTION_RECOMMENDATION_REQUEST_SCOPE",
    ),
    ShadowTransition(
        revision=26,
        name="controlled production recommendation authorization grant",
        kind="grant",
        from_revision=25,
        from_next_stage_constant="POST_CONTROLLED_PRODUCTION_RECOMMENDATION_REQUEST_NEXT_STAGE",
        to_revision=26,
        to_next_stage_constant="POST_CONTROLLED_PRODUCTION_RECOMMENDATION_GRANT_NEXT_STAGE",
        plan_mode="post_controlled_production_recommendation_grant",
        expect_flag_name="expect_controlled_production_recommendation_grant_filed",
        bundle_revision_constant="POST_CONTROLLED_PRODUCTION_RECOMMENDATION_GRANT_BUNDLE_REVISION",
        payload_verifier_name="_verify_controlled_production_recommendation_grant_payload",
        strip_fn_name="_without_controlled_production_recommendation_grant_payload",
        apply_fn_name="apply_production_scoped_shadow_controlled_production_recommendation_authorization_grant",
        section_verifier_name="_verify_controlled_production_recommendation_grant_section",
        filed_marker_path=(
            "authorization.prod_scoped_shadow_controlled_production_recommendation_authorization_granted"
        ),
        scope_constant="CONTROLLED_PRODUCTION_RECOMMENDATION_GRANT_SCOPE",
    ),
    ShadowTransition(
        revision=27,
        name="controlled production recommendation pilot run",
        kind="run",
        from_revision=26,
        from_next_stage_constant="POST_CONTROLLED_PRODUCTION_RECOMMENDATION_GRANT_NEXT_STAGE",
        to_revision=27,
        to_next_stage_constant="POST_CONTROLLED_PRODUCTION_RECOMMENDATION_PILOT_RUN_NEXT_STAGE",
        plan_mode="post_controlled_production_recommendation_pilot_run",
        expect_flag_name="expect_controlled_production_recommendation_pilot_run_filed",
        bundle_revision_constant="POST_CONTROLLED_PRODUCTION_RECOMMENDATION_PILOT_RUN_BUNDLE_REVISION",
        payload_verifier_name="_verify_controlled_production_recommendation_pilot_run_payload",
        strip_fn_name="_without_controlled_production_recommendation_pilot_run_payload",
        apply_fn_name="apply_production_scoped_shadow_controlled_production_recommendation_pilot_run",
        section_verifier_name="_verify_controlled_production_recommendation_pilot_run_section",
        filed_marker_path=(
            "execution.prod_scoped_shadow_controlled_production_recommendation_pilot_executed"
        ),
    ),
    ShadowTransition(
        revision=28,
        name="controlled production recommendation pilot review",
        kind="review",
        from_revision=27,
        from_next_stage_constant="POST_CONTROLLED_PRODUCTION_RECOMMENDATION_PILOT_RUN_NEXT_STAGE",
        to_revision=28,
        to_next_stage_constant="POST_CONTROLLED_PRODUCTION_RECOMMENDATION_PILOT_REVIEW_ACCEPTED_NEXT_STAGE",
        plan_mode="post_controlled_production_recommendation_pilot_review",
        expect_flag_name="expect_controlled_production_recommendation_pilot_review_filed",
        bundle_revision_constant="POST_CONTROLLED_PRODUCTION_RECOMMENDATION_PILOT_REVIEW_BUNDLE_REVISION",
        payload_verifier_name="_verify_controlled_production_recommendation_pilot_review_payload",
        strip_fn_name="_without_controlled_production_recommendation_pilot_review_payload",
        apply_fn_name="apply_production_scoped_shadow_controlled_production_recommendation_pilot_review",
        section_verifier_name="_verify_controlled_production_recommendation_pilot_review_section",
        filed_marker_path=(
            "review.prod_scoped_shadow_controlled_production_recommendation_pilot_reviewed"
        ),
    ),
    ShadowTransition(
        revision=29,
        name="limited production recommendation rollout authorization request",
        kind="request",
        from_revision=28,
        from_next_stage_constant="POST_CONTROLLED_PRODUCTION_RECOMMENDATION_PILOT_REVIEW_ACCEPTED_NEXT_STAGE",
        to_revision=29,
        to_next_stage_constant="POST_LIMITED_PRODUCTION_RECOMMENDATION_ROLLOUT_REQUEST_NEXT_STAGE",
        plan_mode="post_limited_production_recommendation_rollout_request",
        expect_flag_name="expect_limited_production_recommendation_rollout_request_filed",
        bundle_revision_constant="POST_LIMITED_PRODUCTION_RECOMMENDATION_ROLLOUT_REQUEST_BUNDLE_REVISION",
        payload_verifier_name="_verify_limited_production_recommendation_rollout_request_payload",
        strip_fn_name="_without_limited_production_recommendation_rollout_request_payload",
        apply_fn_name="apply_production_scoped_shadow_limited_production_recommendation_rollout_authorization_request",
        section_verifier_name="_verify_limited_production_recommendation_rollout_request_section",
        prior_chain_verifier_name="_require_limited_production_recommendation_rollout_request_prior_chain",
        filed_marker_path=(
            "authorization.prod_scoped_shadow_limited_production_recommendation_rollout_authorization_requested"
        ),
        scope_constant="LIMITED_PRODUCTION_RECOMMENDATION_ROLLOUT_REQUEST_SCOPE",
    ),
    ShadowTransition(
        revision=30,
        name="limited production recommendation rollout authorization grant",
        kind="grant",
        from_revision=29,
        from_next_stage_constant="POST_LIMITED_PRODUCTION_RECOMMENDATION_ROLLOUT_REQUEST_NEXT_STAGE",
        to_revision=30,
        to_next_stage_constant="POST_LIMITED_PRODUCTION_RECOMMENDATION_ROLLOUT_GRANT_NEXT_STAGE",
        plan_mode="post_limited_production_recommendation_rollout_grant",
        expect_flag_name="expect_limited_production_recommendation_rollout_grant_filed",
        bundle_revision_constant="POST_LIMITED_PRODUCTION_RECOMMENDATION_ROLLOUT_GRANT_BUNDLE_REVISION",
        payload_verifier_name="_verify_limited_production_recommendation_rollout_grant_payload",
        strip_fn_name="_without_limited_production_recommendation_rollout_grant_payload",
        apply_fn_name="apply_production_scoped_shadow_limited_production_recommendation_rollout_authorization_grant",
        section_verifier_name="_verify_limited_production_recommendation_rollout_grant_section",
        prior_chain_verifier_name="_require_limited_production_recommendation_rollout_request_prior_chain",
        filed_marker_path=(
            "authorization.prod_scoped_shadow_limited_production_recommendation_rollout_authorization_granted"
        ),
        scope_constant="LIMITED_PRODUCTION_RECOMMENDATION_ROLLOUT_GRANT_SCOPE",
    ),
)

_BY_REVISION = {transition.revision: transition for transition in TRANSITIONS}
_BY_PLAN_MODE = {transition.plan_mode: transition for transition in TRANSITIONS}
_BY_EXPECT_FLAG = {
    transition.expect_flag_name: transition
    for transition in TRANSITIONS
    if transition.expect_flag_name is not None
}


def transition_by_revision(revision: int) -> ShadowTransition:
    return _BY_REVISION[revision]


def transition_by_plan_mode(plan_mode: str) -> ShadowTransition:
    return _BY_PLAN_MODE[plan_mode]


def transition_by_expect_flag(flag_name: str) -> ShadowTransition | None:
    return _BY_EXPECT_FLAG.get(flag_name)


def ordered_transitions_desc() -> tuple[ShadowTransition, ...]:
    return tuple(sorted(TRANSITIONS, key=lambda transition: transition.revision, reverse=True))


def all_plan_modes() -> tuple[str, ...]:
    return tuple(transition.plan_mode for transition in TRANSITIONS)
